<?php
/**
 * HYPERPC - The shop of powerful computers.
 *
 * This file is part of the HYPERPC package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package     HYPERPC
 * @license     Proprietary
 * @copyright   Proprietary https://hyperpc.ru/license
 * @link        https://github.com/HYPER-PC/HYPERPC".
 *
 * @author      Artem Vyshnevskiy
 */

defined('_JEXEC') or die('Restricted access');

use JBZoo\Data\JSON;
use HYPERPC\ORM\Table\Table;

/**
 * Class HyperPcTableMoysklad_Products
 *
 * @since   2.0
 */
class HyperPcTableMoysklad_Products extends Table
{

    /**
     * HyperPcTableMoysklad_Products constructor.
     *
     * @param   \JDatabaseDriver $db
     *
     * @throws  \Exception
     *
     * @since   2.0
     */
    public function __construct(\JDatabaseDriver $db)
    {
        parent::__construct(HP_TABLE_MOYSKLAD_PRODUCTS, HP_TABLE_PRIMARY_KEY, $db);

        $this->_autoincrement = false;
    }

    /**
     * Method to provide a shortcut to binding, checking and storing a Table instance to the database table.
     *
     * @param   array|object $src
     * @param   string $orderingFilter
     * @param   string $ignore
     *
     * @return  bool
     *
     * @throws  \JBZoo\SimpleTypes\Exception
     *
     * @since   2.0
     */
    public function save($src, $orderingFilter = '', $ignore = '')
    {
        if (isset($src['processingplan_id']) && $src['processingplan_id'] === 0) {
            $ignore = 'processingplan_id';
        }

        return parent::save($src, $orderingFilter, $ignore); // TODO: Change the autogenerated stub
    }

    /**
     * Overloaded bind function.
     *
     * @param   array|object  $array
     * @param   string        $ignore
     *
     * @return  bool
     *
     * @throws  \Exception
     * @throws  \RuntimeException
     * @throws  \InvalidArgumentException
     *
     * @since   2.0
     */
    public function bind($array, $ignore = '')
    {
        if (array_key_exists('configuration', $array)) {
            $array['configuration'] = (new JSON($array['configuration']))->write();
        } else {
            $array['configuration'] = '{}';
        }

        return parent::bind($array, $ignore);
    }
}
