<?php
/**
 * HYPERPC - The shop of powerful computers.
 *
 * This file is part of the HYPERPC package.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package     HYPERPC
 * @license     Proprietary
 * @copyright   Proprietary https://hyperpc.ru/license
 * @link        https://github.com/HYPER-PC/HYPERPC".
 *
 * @author      ROman Evsyukov
 */

use HYPERPC\App;
use Joomla\CMS\Form\Field\TextField;
use Joomla\CMS\Language\LanguageHelper;

defined('_JEXEC') or die('Restricted access');

/**
 * Class JFormFieldHPText
 *
 * @since 2.0
 */
class JFormFieldHPText extends TextField
{
    /**
     * The form field type.
     *
     * @var     string
     *
     * @since   2.0
     */
    protected $type = 'HPText';

    public function setup(\SimpleXMLElement $element, $value, $group = null)
    {
        if (is_array($value)) {
            $app = App::getInstance();

            $contentLangs    = LanguageHelper::getContentLanguages();
            $defaultLangCode = $app->getDefaultLanguageCode();
            $langSef         = $contentLangs[$defaultLangCode]->sef;

            $value = $value[$langSef];
        }

        return parent::setup($element, $value, $group); // TODO: Change the autogenerated stub
    }
}
